### ISSUE TITLE
No + button when using activity in version 2.1

### ISSUE THREAD

**Issue by wujek-srujek** [passy/Android-DirectoryChooser#45]
When the DirectoryChooserActivity is used, the +_button to add a new directory is not shown. But the activity requires the EXTRA_NEW_DIR_NAME intent extra to be set, otherwise it results in exceptions. I think the code responsible for this might be the following from DirectoryChooserFragment:202-204:

if (!getShowsDialog()) {
            mBtnCreateFolder.setVisibility(View.GONE);
        }
I.e. if the fragment is not shown as a dialog, the create folder button is hidden.

Am I missing something, or is there another way to create the folder using activity or non-dialog fragment?

**Comment by passy** [comment]
Please re-open if this is still happening with 3.0.

**Comment by mendhak** [comment]
Not seeing a `+` in  v3.2:

![image](https://cloud.githubusercontent.com/assets/746276/13369032/41d8ee86-dce8-11e5-948e-197e4001ddb0.png)

Fragment works just fine

**Comment by passy** [comment]
Thanks! I don't have a good way at the moment to repro this. If someone with a working example could hop into the debugger and check what's going wrong, I'd appreciate that.

**Comment by secu2** [comment]
My interpretation of this problem is that your parent activity has a NoActionBarTheme.
And it looks like to me that the create folder button is designed to be in the ActionBar for the activity mode.

The method getShowsDialog() returns false when called in activity mode, maybe you should also check for a NoActionBarTheme to show the + button.

Currently I used this in the manifest as a workaround : 
`<activity
            android:name="net.rdrei.android.dirchooser.DirectoryChooserActivity"
            android:theme="@style/Theme.AppCompat.Light">
 </activity>`
